Aco agent multi map movement
S010MON/multi-agent-surveillance pull request #184
Opened 2022-03-09 11:31 UTC by trav-d13

Please keep in mind the Agent clashing interactions still need to be resolved. Once resolved, should allow for the creation of patrols by the agents after exploration phase

2022-03-09 12:48 UTC, S010MON approved these changes
All of your methods are public, is this required?  Make any implementation specific methods private (as much as possible) to increase encapsulation.

The code looks good and passes all the tests; I haven't looked through the tests in detail, but approved!

2022-03-09 12:48 UTC, S010MON commented on src/main/java/app/model/agents/ACO/AcoAgent.java
> +    {
This is a very nice method! Clean

2022-03-09 12:48 UTC, S010MON commented on src/main/java/app/model/agents/ACO/AcoAgent.java
> +        System.out.println("Cardinal Point not found");
Consider a runtime error instead?
```java
throw new RuntimeException("Cardinal Point not found");
```

2022-03-09 12:48 UTC, S010MON commented on src/main/java/app/model/agents/ACO/AcoAgent.java
> +        if(detectedAngle < (targetAngle + epsilon) && detectedAngle > (targetAngle - epsilon))
change to return value directly
```java
return detectedAngle < (targetAngle + epsilon) && detectedAngle > (targetAngle - epsilon);
```

2022-03-09 12:48 UTC, S010MON commented on src/main/java/app/model/agents/ACO/AcoAgent.java
> +
random space?

2022-03-09 12:53 UTC, S010MON commented on src/main/java/app/model/agents/ACO/AcoAgent.java
> +        if(detectedAngle < (targetAngle + epsilon) && detectedAngle > (targetAngle - epsilon))
Rather than

```java
if(condition)
   return true;
else
   return false;
```

2022-03-09 16:06 UTC, MatthewFoster02 approved these changes
Get cardinal point not found error when running but the style and code looks good.

2022-03-09 19:02 UTC, Jolijn2020 commented on src/main/java/app/controller/linAlg/Vector.java
> +        if(roundedAngle == 360.0)
don't you need to take into account that doubles aren't precise?

for example:

if( Math.abs(roundedAngle-360.0) < 0.00001 )
```suggestion
        if(Math.abs(roundedAngle-360.0) < 0.00001 )```

2022-03-09 19:06 UTC, Jolijn2020 commented on src/main/java/app/model/Grid/Grid.java
> +    public double getCellSize()
can use a @Getter for this

2022-03-09 19:18 UTC, S010MON requested changes
I'm getting a consistent error:
```java
Cardinal Point not found
Cardinal Point not found
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "app.controller.graphicsEngine.Ray.rayLength()" because "cardinalRays[i]" is null
	at app@1.0-SNAPSHOT/app.model.agents.ACO.AcoAgent.determineAvailableMovements(AcoAgent.java:172)
	at app@1.0-SNAPSHOT/app.model.agents.ACO.AcoAgent.determineMovesAllScenarios(AcoAgent.java:88)
	at app@1.0-SNAPSHOT/app.model.agents.ACO.AcoAgent.move(AcoAgent.java:55)
	at app@1.0-SNAPSHOT/app.controller.GameEngine.tick(GameEngine.java:42)

```

It seems that the addition of throwing an exception has exposed a problem that was handled with print statements.  
> Consider a runtime error instead?
> 
> ```java
> throw new RuntimeException("Cardinal Point not found");
> ```

Up to you to advise if this is a serious error or trivial and should be returned to a `System.out.println` for Info logging

2022-03-10 11:52 UTC, S010MON submitted a review, later dismissed

2022-03-10 11:55 UTC, MatthewFoster02 submitted a review, later dismissed

2022-03-11 18:38 UTC, S010MON commented
Dude ... two people reviewed this request and you just left it, now it's out of date with conflicts.  Not cool

2022-03-11 20:56 UTC, merged