Fix for WF agent not recognising walls and initial wall following position
S010MON/multi-agent-surveillance pull request #298
Opened 2022-05-07 14:38 UTC by laurajogi

WF agent now detects walls properly again and should act reliably. Also each agent detects its own initial position where it started wall following.

2022-05-14 11:02 UTC, laurajogi commented
The WF agent works as it's supposed to (finally) and starts following walls again if it finds an unexplored one. Will create different variants of the agent for experiments in a new branch now.

2022-05-15 10:16 UTC, S010MON requested changes
This seems to fix the issue, but I am getting weird freezing after running the simulation for more than 20 seconds.  There might be a memory leak somewhere that is causing this?  I don't know if anyone else is having the same issue, but this doesn't occur on the `master` branch.

2022-05-15 10:16 UTC, S010MON commented on src/main/java/app/model/Map.java
> +            //Agent intruder = new DirectionFollowAgent(srt, dir, 10, Type.INTRUDER, targetDirection(srt));
Is this code being used?  If not it's probably best to remove to keep it clean

2022-05-15 10:23 UTC, S010MON commented
https://user-images.githubusercontent.com/10490509/168468036-d54f4dd4-0d92-4e5d-8559-bd7a193a0ae8.mp4

This is a video of the issues I'm getting

2022-05-16 14:05 UTC, S010MON commented
![Screenshot from 2022-05-16 16-03-40](https://user-images.githubusercontent.com/10490509/168610816-e4d3a053-f464-4b1e-a8b3-ae28679d05b4.png)

So the slowdowns seems to be eating a load of CPU, but the memory isn't changed much.  SO not a memory leak, but likely you're doing a really expensive operation that should be checked out later on.

I've approved the PR

2022-05-16 14:07 UTC, S010MON approved these changes

2022-05-16 15:25 UTC, S010MON submitted a review, later dismissed

2022-05-17 11:42 UTC, trav-d13 approved these changes
Looks good. Runs well my side

2022-05-17 12:12 UTC, MatthewFoster02 approved these changes

2022-05-17 12:21 UTC, merged