Created SaveMap class to save map as .txt file
S010MON/multi-agent-surveillance pull request #68
Opened 2022-02-08 19:15 UTC by Jolijn2020

also created test for it

currently only creates file in right place with right name, will enhance later.

copied from original branch, to avoid merging conflicts

2022-02-08 19:43 UTC, S010MON requested changes

2022-02-08 19:43 UTC, S010MON commented on src/main/java/app/model/map/SaveMap.java
> +    private final String FILE_PATH = "src/main/java/app/model/map/files/";
Can you save files in the `src/main/java/resources` folder instead

2022-02-08 19:43 UTC, S010MON commented on src/test/java/jgfx/javagradlefx/SaveMapTest.java
> +            deleteIfExists(path);
When testing files, It's good practice to write a `@BeforeAll` and `@AfterAll` method that does your build and breakdown for all the tests, then you only have to do one of these deletes in the file

2022-02-08 19:56 UTC, Jolijn2020 commented on src/main/java/app/controller/Settings.java
> +    private String name;
added it to FileParser

2022-02-08 20:11 UTC, Jolijn2020 commented
implemented requested changes

2022-02-09 07:18 UTC, S010MON approved these changes

2022-02-09 08:26 UTC, merged